name: CDK Deployment

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install dependencies
    - name: Install Node.js and dependencies
      run: |
        npm install -g aws-cdk
        npm install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'af-south-1'

    # Deploy CDK Stack
    - name: Deploy CDK Stack
      run: |
        npx cdk deploy --require-approval=never
